apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: svcsealink
  name: svcsealink
spec:
  ports:
  - name: 5678-8084
    port: 5678
    protocol: TCP
    targetPort: 8084
  selector:
    app: sealink
  type: ClusterIP
status:
  loadBalancer: {}
